routes/web.php
<?php

use App\Http\Controllers\Admin\ArticleController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\TagController;
use App\Http\Controllers\ArticleController as HomeController;
use App\Http\Controllers\CategoryController as AllArticlesWithThisCategory;
use App\Http\Controllers\TagController as AllArticlesWithThisTag;
use Illuminate\Support\Facades\Route;

Route::get('/', [HomeController::class, 'index']);

Route::get('articles/{article}', [HomeController::class, 'show'])
    ->whereNumber('article')
    ->name('articles.show');

Route::group(['middleware' => 'auth', 'prefix' => 'admin'], function () {
    Route::view('/', 'admin.index')->name('admin');
    Route::resources([
        'articles' => ArticleController::class,
        'categories' => CategoryController::class,
        'tags' => TagController::class
    ], ['except' => 'show']);
});

Route::get('categories/{category}', AllArticlesWithThisCategory::class)->name('categories.show');
Route::get('tags/{tag}', AllArticlesWithThisTag::class)->name('tags.show');

Route::view('about', 'about')->name('about');

require __DIR__.'/auth.php';

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class Article extends Model
{
    use HasFactory;

    /**
     * @var array
     */
    protected $guarded = [];

    /**
     * @return string
     */
    public function getTeaserAttribute(): string
    {
        return Str::limit($this->content, 120);
    }

    /**
     * @return string
     */
    public function getImageUrl(): string
    {
        if (Str::startsWith($this->image, 'http')) {
            return $this->image;
        }

        if (! $this->image) return 'https://via.placeholder.com/384x160?text=No+image';

        return asset('storage/' . $this->image);
    }

    /**
     * @return string
     */
    public function getImageLinkAttribute(): string
    {
        return $this->isUploadedImage() ? '' : ($this->image ?? '');
    }

    /**
     * @param array $fields
     */
    public function prepareToInsert(array &$fields)
    {
        if (request()->file('image')) {
            $fields['image'] = request()->file('image')->store('images', 'public');
        } elseif ($fields['image_link']) {
            $fields['image'] = $fields['image_link'];
        }

        unset($fields['image_link']);
    }

    /**
     * @param array $fields
     * @return array
     */
    public function getPreparedTags(array &$fields): array
    {
        if (! isset($fields['tags'])) return [];

        $tags = [];
        foreach ($fields['tags'] as $tagName) {
            $tag = Tag::firstOrCreate(['name' => $tagName]);
            $tags[] = $tag->id;
        }

        unset($fields['tags']);

        return $tags;
    }

    /**
     * @param array $fields
     */
    public function prepareToUpdate(array &$fields)
    {
        if (request()->hasFile('image')) {
            $this->removeImage();

            $fields['image'] = request()->file('image')->store('images', 'public');
        } elseif ($fields['image_link']) {
            $fields['image'] = $fields['image_link'];
        }

        unset($fields['image_link']);

        $fields['updated_at'] = now();
    }

    public function removeImage()
    {
        if ($this->isUploadedImage()) {
            Storage::disk('public')->delete($this->image);
        }
    }

    /**
     * @return BelongsTo
     */
    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * @return BelongsToMany
     */
    public function tags(): BelongsToMany
    {
        return $this->belongsToMany(Tag::class);
    }

    /**
     * @return bool
     */
    private function isUploadedImage(): bool
    {
        return $this->image && Str::startsWith($this->image, 'images/');
    }
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\ArticleRequest;
use App\Models\Article;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index(): Application|Factory|View
    {
        $articles = Article::with('category')
            ->withCount('tags')
            ->latest('updated_at')
            ->paginate(6);

        return view('admin.articles.index', compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create(): View|Factory|Application
    {
        return view('admin.articles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ArticleRequest $request
     * @return RedirectResponse
     */
    public function store(ArticleRequest $request): RedirectResponse
    {
        $fields = $request->validated();

        $article = new Article;
        $article->prepareToInsert($fields);
        $tags = $article->getPreparedTags($fields);
        $article->fill($fields);
        $article->save();
        $article->tags()->attach($tags);

        return redirect()->route('articles.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Article $article
     * @return Application|Factory|View
     */
    public function edit(Article $article): Application|Factory|View
    {
        return view('admin.articles.edit', compact('article'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ArticleRequest $request
     * @param Article $article
     * @return RedirectResponse
     */
    public function update(ArticleRequest $request, Article $article): RedirectResponse
    {
        $fields = $request->validated();

        $article->prepareToUpdate($fields);
        $article->tags()->sync($article->getPreparedTags($fields));
        $article->update($fields);

        return redirect()->route('articles.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Article $article
     * @return RedirectResponse
     */
    public function destroy(Article $article): RedirectResponse
    {
        $article->removeImage();
        $article->delete();

        return back();
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Article;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index(): View|Factory|Application
    {
        $articles = Article::with('tags')
            ->latest()
            ->paginate(9);

        return view('articles.index', compact('articles'));
    }

    /**
     * Display the specified resource.
     *
     * @param Article $article
     * @return Application|Factory|View
     */
    public function show(Article $article): View|Factory|Application
    {
        $nextArticle = $article->where('created_at', '>', $article->created_at)
            ->oldest()
            ->first();

        $prevArticle = $article->where('created_at', '<', $article->created_at)
            ->latest()
            ->first();

        return view('articles.show', compact('article', 'nextArticle', 'prevArticle'));
    }
}

app/View/Components/AdminLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AdminLayout extends Component
{
    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('layouts.admin');
    }
}

resources/views/admin/articles/_scripts.blade.php
@push('css')
<link href="https://cdn.jsdelivr.net/npm/slim-select@1/dist/slimselect.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/suneditor@latest/dist/css/suneditor.min.css" rel="stylesheet">
@endpush

<script src="https://cdn.jsdelivr.net/npm/suneditor@latest/dist/suneditor.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/slim-select@1/dist/slimselect.min.js"></script>
<script>
    const sunEditor = SUNEDITOR.create('content')
    sunEditor.onChange = () => sunEditor.save()

    new SlimSelect({
        select: '#category_id'
    })

    new SlimSelect({
        select: '#tags',
        closeOnSelect: false,
        hideSelectedOption: true,
        addable: function (value) {
            return {
                text: value.toLowerCase(),
                value: value.toLowerCase()
            }
        }
    })
</script>

resources/views/admin/articles/create.blade.php
<x-admin-layout>
    <x-slot name="header">
        {{ __('New article') }}
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">

                    <!-- Validation Errors -->
                    <x-auth-validation-errors class="mb-4" :errors="$errors" />

                    <form method="POST" action="{{ route('articles.store') }}" enctype="multipart/form-data">
                        @csrf

                        <div>
                            <x-label for="title" :value="__('Article title')" />
                            <x-input id="title" class="block mt-1 w-full" type="text" name="title" :value="old('title')" required autofocus />
                        </div>

                        <div class="mt-4">
                            <x-label for="category_id" :value="__('Category')" />
                            <select name="category_id" id="category_id">

                                @foreach ($categories as $category)
                                    <option value="{{ $category->id }}"{{ old('category_id') === $category->id ? ' selected' : '' }}>{{ $category->name }}</option>
                                @endforeach

                            </select>
                        </div>

                        <div class="mt-4">
                            <x-label for="tags" :value="__('Tags')" />
                            <select name="tags[]" id="tags" multiple>

                                @foreach ($tags as $tag)
                                    <option value="{{ $tag->name }}"{{ old('tags') && in_array($tag->name, old('tags')) ? ' selected' : '' }}>{{ $tag->name }}</option>
                                @endforeach

                            </select>
                        </div>

                        <div class="mt-4">
                            <x-label for="content" :value="__('Content')" />
                            <x-textarea name="content" id="content" cols="10" rows="8" placeholder="What do you want to tell the world?">{{ old('content') }}</x-textarea>
                        </div>

                        <div class="mt-4">
                            <x-label for="image_link" :value="__('Image link')" />
                            <x-input id="image_link" class="block mt-1 w-full" type="url" name="image_link" :value="old('image_link')" placeholder="You can specify any image link or upload a desired picture from your computer" />
                        </div>

                        <div class="mt-4">
                            <div class="flex w-full items-center justify-center bg-grey-lighter">
                                <label class="w-64 flex flex-col items-center px-4 py-6 bg-white text-blue rounded-lg shadow-sm tracking-wide uppercase border border-blue cursor-pointer hover:bg-blue hover:text-blue-400">
                                    <svg class="w-8 h-8" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                        <path d="M16.88 9.1A4 4 0 0 1 16 17H5a5 5 0 0 1-1-9.9V7a3 3 0 0 1 4.52-2.59A4.98 4.98 0 0 1 17 8c0 .38-.04.74-.12 1.1zM11 11h3l-4-4-4 4h3v3h2v-3z"></path>
                                    </svg>
                                    <span class="mt-2 text-base leading-normal">{{ __('Image') }}</span>
                                    <input type="file" name="image" class="hidden" accept="image/*">
                                </label>
                            </div>
                        </div>

                        <div class="flex items-center justify-end mt-4">
                            <a class="underline text-sm text-gray-600 hover:text-gray-900" href="{{ route('articles.index') }}">
                                {{ __('Back to the article list') }}
                            </a>

                            <x-button class="ml-3">
                                {{ __('Create') }}
                            </x-button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>

    @include('admin.articles._scripts')
</x-admin-layout>

resources/views/admin/articles/edit.blade.php
<x-admin-layout>
    <x-slot name="header">
        {{ __('Edit article') }}
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">

                    <!-- Validation Errors -->
                    <x-auth-validation-errors class="mb-4" :errors="$errors" />

                    <form method="POST" action="{{ route('articles.update', $article) }}" enctype="multipart/form-data">
                        @csrf
                        @method('PATCH')

                        <div>
                            <x-label for="title" :value="__('Article title')" />
                            <x-input id="title" class="block mt-1 w-full" type="text" name="title" value="{{ $article->title }}" required autofocus />
                        </div>

                        <div class="mt-4">
                            <x-label for="category_id" :value="__('Category')" />
                            <select name="category_id" id="category_id">

                                @foreach ($categories as $category)
                                    <option value="{{ $category->id }}"{{ $article->category_id === $category->id ? ' selected' : '' }}>{{ $category->name }}</option>
                                @endforeach

                            </select>
                        </div>

                        <div class="mt-4">
                            <x-label for="tags" :value="__('Tags')" />
                            <select name="tags[]" id="tags" multiple>

                                @foreach ($tags as $tag)
                                    <option value="{{ $tag->name }}"{{ in_array($tag->name, $article->tags->pluck('name')->toArray()) ? ' selected' : '' }}>{{ $tag->name }}</option>
                                @endforeach

                            </select>
                        </div>

                        <div class="mt-4">
                            <x-label for="content" :value="__('Content')" />
                            <x-textarea name="content" id="content" cols="10" rows="8" placeholder="What do you want to tell the world?">{{ $article->content }}</x-textarea>
                        </div>

                        <div class="mt-4">
                            <x-label for="image_link" :value="__('Image link')" />
                            <x-input id="image_link" class="block mt-1 w-full" type="url" name="image_link" value="{{ $article->image_link }}" placeholder="You can specify any image link or upload a desired picture from your computer" />
                        </div>

                        <div class="mt-4">
                            <div class="flex w-full items-center justify-center bg-grey-lighter">
                                <label class="w-64 flex flex-col items-center px-4 py-6 bg-white text-blue rounded-lg shadow-sm tracking-wide uppercase border border-blue cursor-pointer hover:bg-blue hover:text-blue-400">
                                    <svg class="w-8 h-8" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                        <path d="M16.88 9.1A4 4 0 0 1 16 17H5a5 5 0 0 1-1-9.9V7a3 3 0 0 1 4.52-2.59A4.98 4.98 0 0 1 17 8c0 .38-.04.74-.12 1.1zM11 11h3l-4-4-4 4h3v3h2v-3z"></path>
                                    </svg>
                                    <span class="mt-2 text-base leading-normal">{{ __('Image') }}</span>
                                    <input type="file" name="image" class="hidden" accept="image/*">
                                </label>
                            </div>
                        </div>

                        <div class="flex items-center justify-end mt-4">
                            <a class="underline text-sm text-gray-600 hover:text-gray-900" href="{{ route('articles.index') }}">
                                {{ __('Back to the article list') }}
                            </a>

                            <x-button class="ml-3">
                                {{ __('Update') }}
                            </x-button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>

    @include('admin.articles._scripts')
</x-admin-layout>

resources/views/admin/articles/index.blade.php
<x-admin-layout>
    <x-slot name="header">
        {{ __('Manage articles') }}
    </x-slot>

    <div class="bg-white pb-4 px-4 rounded-md w-full">
        <div class="w-full flex justify-end px-2 mt-2">
            <div class="w-full sm:w-auto inline-block relative">
                <x-button-link :href="route('articles.create')">
                    {{ __('Add article') }}
                </x-button-link>
            </div>
        </div>
        <div class="overflow-x-auto mt-6">
            <table class="table-auto border-collapse w-full">
                <thead>
                    <tr class="rounded-lg text-sm font-medium text-gray-700 text-left" style="font-size: 0.9674rem">
                        <th class="px-4 py-2 bg-gray-200" style="background-color:#f8f8f8">Title</th>
                        <th class="px-4 py-2" style="background-color:#f8f8f8">Category</th>
                        <th class="px-4 py-2" style="background-color:#f8f8f8">Image</th>
                        <th class="px-4 py-2" style="background-color:#f8f8f8">Tags</th>
                        <th class="px-4 py-2" style="background-color:#f8f8f8">Updated at</th>
                        <th class="px-4 py-2 flex justify-end" style="background-color:#f8f8f8">Actions</th>
                    </tr>
                </thead>
                <tbody class="text-sm font-normal text-gray-700">

                @foreach ($articles as $article)
                    <tr class="hover:bg-gray-100 border-b border-gray-200 py-10">
                        <td class="px-4 py-4">
                            <a class="text-sm text-gray-600 hover:text-gray-900" href="{{ route('articles.show', $article) }}">
                                {{ $article->title }}
                            </a>
                        </td>
                        <td class="px-4 py-4">{{ $article->category->name }}</td>
                        <td class="px-4 py-4">
                            <img class="w-24" src="{{ $article->getImageUrl() }}">
                        </td>
                        <td class="px-4 py-4">
                            <span class="relative inline-block px-3 py-1 font-semibold text-green-900 leading-tight">
                                <span aria-hidden class="absolute inset-0 bg-green-200 opacity-50 rounded-full"></span>
                                <span class="relative text-xs">
                                    {{ $article->tags_count }}
                                </span>
                            </span>
                        </td>
                        <td class="px-4 py-4">{{ $article->updated_at->diffForHumans() }}</td>
                        <td class="px-4 py-4 flex justify-end">
                            <a class="mr-3 text-sm bg-blue-500 hover:bg-blue-700 text-white py-1 px-2 rounded focus:outline-none focus:shadow-outline" href="{{ route('articles.edit', $article) }}">
                                {{ __('Edit') }}
                            </a>
                            <form method="POST" action="{{ route('articles.destroy', $article) }}">
                                @csrf
                                @method('DELETE')

                                <button type="submit" onclick="return confirm('Sure?')" class="text-sm bg-red-500 hover:bg-red-700 text-white py-1 px-2 rounded focus:outline-none focus:shadow-outline">{{ __('Remove') }}</button>
                            </form>
                        </td>
                    </tr>
                @endforeach

                </tbody>
            </table>
        </div>

        {{ $articles->links() }}

    </div>
</x-admin-layout>